### ISSUE TITLE
Cancellation Token to async methods

### ISSUE THREAD

**Issue by MarkBQE** [intuit/TSheets-V1-DotNET-SDK#11]
How do we pass cancellation token to async methods, I need to cancel the get TimeSheets Async method gracefully, I do not see an overload of this method where I can pass in the cancellation token

var a = await this.client.GetTimesheetsAsync(new TimesheetFilter { StartDate = DateTimeOffset.Parse(startdate), 
                EndDate= DateTimeOffset.Parse(endDate)});

**Comment by dustinsweet** [comment]
Great question.  It's not available yet, but we'll add support for cancellation within the next couple of weeks.

**Comment by MarkBQE** [comment]
Dustin,I am pasting this code as a work around for cancelling long running task for  situations where you encounter a method that does not support cancellation token in-case someone else is looking for a similar solution. I am glad that you planning to roll-out support for cancellation in few weeks, excited!!


        public async Task<(IList<Timesheet>, ResultsMeta)> GetTimeSheetAsync(string startdate, string endDate, CancellationToken cs)
        {
            var a = SettingsGlobal.TSheetsAccessToken;
            // We create a TaskCompletionSource of (IList<Timesheet>, ResultsMeta)
            var taskCompletionSource = new TaskCompletionSource<(IList<Timesheet>, ResultsMeta)>();

            // Registering a lambda into the cancellationToken
            cs.Register(() =>
            {
                // We received a cancellation message, cancel the TaskCompletionSource.Task
                taskCompletionSource.TrySetCanceled();
            });

            var task = this.client.GetTimesheetsAsync(new TimesheetFilter
            {
                StartDate = DateTimeOffset.Parse(startdate),
                EndDate = DateTimeOffset.Parse(endDate)
            }); ;

            // Wait for the task to finish 
            var completedTask = await Task.WhenAny(task, taskCompletionSource.Task);

            return await completedTask;

            }

**Comment by dustinsweet** [comment]
CancellationToken support has been added in newly release v1.2.0.  Thanks!
