### ISSUE TITLE
Unhandled exception on GetDateTimeOffsetValue

### ISSUE THREAD

**Issue by PedroB801** [intuit/TSheets-V1-DotNET-SDK#17]
Unhandled exception in GetDateTimeOffsetValue due to an empty string not being able to be parsed

The empty string in question is returned by Supplemental Data on GetTimesheets

An employee with no previously submitted time or approved time will return empty strings in the following fields:
supplemental_data.users.XXXXX.submitted_to
supplemental_data.users.XXXXX.approved_to

A way to fix it in the client API is to check for string.empty in addition to UninitializedDateString
private static DateTimeOffset GetDateTimeOffsetValue(string stringValue, string format)
        {
            return (stringValue.Equals(string.Empty) || stringValue.Equals(UninitializedDateString)) <--New Code to fix issue
                ? DateTimeOffset.MinValue
                : DateTimeOffset.ParseExact(stringValue, format, CultureInfo.InvariantCulture);
        }

**Comment by dustinsweet** [comment]
Thank you!  Fixed in latest commit to master https://github.com/intuit/TSheets-V1-DotNET-SDK/commit/3868139f184caead3ba62c7c7b72e08dbbafcc47.  New v1.3.1 now available in nuget.
