### ISSUE TITLE
Error when attempting to retrieve ProjectReport with JobcodeId.

### ISSUE THREAD

**Issue by jepark0805** [intuit/TSheets-V1-DotNET-SDK#24]
**Describe the bug**
When trying to retrieve a ProjectReport using JobcodeId's, I get the following error:
<HTML>

<body>

  | Name | Value | Type
-- | -- | -- | --
◢ | InnerException | {"Error converting value \"20370911\" to type 'System.Collections.Generic.IReadOnlyList`1[System.Int64]'. Path 'results.project_report.filters.jobcode_ids', line 17, position 29."} | System.Exception {Newtonsoft.Json.JsonSerializationException}

</body>
</HTML>
I am using the required List<long> parameter to filter with JobcodeId's.
If I do not include JobcodeId's, I am able to pull ProjectReports.

**To Reproduce**

>         public ProjectReport getProjectReport(List<long> jcId, DateTimeOffset startDate, DateTimeOffset endDate)
>         {
>             var filter = new ProjectReportFilter { StartDate =  startDate, EndDate = endDate, JobcodeIds = jcId};
> 
>             ProjectReport projectReport = this.apiClient.GetProjectReport(filter).Item1;
> 
>             return projectReport;
> 
>         }
> 

**Expected behavior**
I expected to retrieve ProjectReportData. 

**Dev Environment (please complete the following information):**
 - OS: Windows 10
 - IDE & Version Visual Studio 2019

**Comment by dustinsweet** [comment]
Hi jepark0805, we're looking into this now.  Hope to have a fix soon.

**Comment by jepark0805** [comment]
Hi Dustin,

Thank you for looking into this! I am now getting the following error after the new update.
![image](https://user-images.githubusercontent.com/8879293/128724783-bfacd3bc-4163-4236-9375-bac4a7f765a4.png)
