### ISSUE TITLE
Error trying to retrieve ProjectReport or ProjectReportData objects.

### ISSUE THREAD

**Issue by jepark0805** [intuit/TSheets-V1-DotNET-SDK#26]
**Describe the bug**
I am now getting the following error after the new update 1.4.2 which addressed retrieving ProjectReport objects with JobcodeId.
![image](https://user-images.githubusercontent.com/8879293/128724783-bfacd3bc-4163-4236-9375-bac4a7f765a4.png)
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Intuit.TSheets
  StackTrace:
   at Intuit.TSheets.Client.Serialization.Converters.EmptyArrayObjectConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

It looks like the bug is originating at EmptyArrayObjectConverter.cs Line 102.
![image](https://user-images.githubusercontent.com/8879293/128728527-c794e07a-286a-4cb6-a839-7c221b4c7d51.png)

**Dev Environment (please complete the following information):**
 - OS: Windows 10
 - IDE & Version Visual Studio 2019

**Comment by dustinsweet** [comment]
Ack, sorry for the trouble - not sure why we didn't see this.  Will prioritize a fix this morning.

-Dustin

**Comment by dustinsweet** [comment]
Thanks for the helpful detail.  Please pick up new version 1.4.3

**Comment by jepark0805** [comment]
Thank you @dustinsweet! Worked like a charm.
