### ISSUE TITLE
PackageLicenseUrl error

### ISSUE THREAD

**Issue by gswartz777** [intuit/TSheets-V1-DotNET-SDK#7]
**Describe the bug**
When initially trying to build this using VS2019 it wouldn't build complaining about .netstandard not being found.  I switched the 3 .net core projects from 2.1 to 2.2 and those errors went away.  But now when trying to build I get the error message - The PackageLicense Url is being deprecated and cannot be used in conjunction with the PackageLicense File or PackageLicense Expression  It's pointing to the NuGet.Build.Tasks.Pack.targets file in C:\Program Files\dotnet\sdk\2.2.401\Sdks\NuGet.Build.Tasks.Pack\build  Any idea what to do?

**To Reproduce**
1. Clone the sdk
2. Open with vs2019
3. Try to build

**Expected behavior**
Expected that the solution would build without errors.

**Dev Environment (please complete the following information):**
 - OS: Windows 10
 - IDE & Version VS 2019

**Comment by dustinsweet** [comment]
Hi Geoff, thanks for reporting this!  I encountered the same issue the very first time I upgraded to VS2019, but then it disappeared on subsequent loads of the solution.  However, I've managed to get a repo on another machine, and I'm working on a solution now.

**Comment by dustinsweet** [comment]
Geoff, can you please pick up latest master (v1.1.2) and give it a try?

**Comment by gswartz777** [comment]
Master builds fine for me now.  Thank you!
